### ISSUE TITLE
Doesn't launch

### ISSUE THREAD

**Issue by klepz** [flathub/com.rafaelmardojai.Blanket#4]
[issue.txt](https://github.com/flathub/com.rafaelmardojai.Blanket/files/5229490/issue.txt)

**Comment by rafaelmardojai** [comment]
Try this and tell me if the issue is fixed:
[com.rafaelmardojai.Blanket.zip](https://github.com/flathub/com.rafaelmardojai.Blanket/files/5229643/com.rafaelmardojai.Blanket.zip)

**Comment by klepz** [comment]
Yes, it works perfectly.
output:
`blanket:2): Gtk-WARNING **: 04:19:07.666: Locale not supported by C library.
	Using the fallback 'C' locale.
`

**Comment by rafaelmardojai** [comment]
I can't get the waning until I run the app with a different LANG than my system `LANG=es_ES.UTF-8`:

```bash
$ LANG=pt_BR flatpak run com.rafaelmardojai.Blanket
(blanket:2): Gtk-WARNING **: 10:15:03.942: Locale not supported by C library.
	Using the fallback 'C' locale.
```

Do you get the same warning from other apps with similar stack like Lollypop?
